<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset 
  name CDATA #REQUIRED
  levels CDATA #IMPLIED  
  span CDATA #IMPLIED
  level CDATA #IMPLIED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
 <!ENTITY layer_real_source_path "/sf/os/mm" >
]>
<SystemDefinition name="os_mm_pkg" schema="1.4.0">
	<systemModel>
  <!-- Common file for prebuild layers-->
  	<layer name="os_layer">
			<module name="mm_mm_plat">
				<unit name="mm_plat" unitID="sos.mm_plat" mrp="" bldFile="&layer_real_source_path;/mm_plat/group"/>
			</module>
			
			<module name="mm_mdfdevvideoext">
				<unit name="mm_mdfdevvideoext" unitID="sos.mm_mdfdevvideoext" mrp="" bldFile="&layer_real_source_path;/mdfdevvideoextensions/group"/>
			</module>
			<module name="mm_camerafw">
				<unit name="mm_camerafw" unitID="sos.mm_camerafw" mrp="" bldFile="&layer_real_source_path;/imagingandcamerafws/camerafw/group"/>
			</module>
			<module name="mm_mmplugins">
				<unit name="mm_cameraplugins" unitID="sos.cameraplugins" mrp="" bldFile="&layer_real_source_path;/mmplugins/cameraplugins/group"/>				
				<unit name="mm_lib3gp" unitID="sos.lib3gp" mrp="" bldFile="&layer_real_source_path;/mmplugins/lib3gp/group"/>				
			</module>
			<module name="mm_mmdevicefw">
				<unit name="mm_mmdevicefw" unitID="sos.mm_mmdevicefw" mrp="" bldFile="&layer_real_source_path;/mmdevicefw/mdf/group"/>
			</module>
			<module name="mm_videohai">
				<unit name="mm_videohai" unitID="sos.mm_videohai" mrp="" bldFile="&layer_real_source_path;/mmhais/videohai/group"/>
				<unit name="mm_dvbhreceiverhai" unitID="sos.mm_dvbhreceiverhai" mrp="" bldFile="&layer_real_source_path;/mmhais/dvbhreceiverhai/hai/dvbh/group"/>				
			</module>
	</layer>		
  </systemModel>
</SystemDefinition>
